### ISSUE TITLE
Annotation @template not found in symfony app

### ISSUE THREAD

**Issue by alamirault** [doctrine/collections#181] opened 2019-03-25 08:59 UTC
When I updated doctrine/collections from 1.5.0 to 1.6.0 I have this error `[Semantical Error] The annotation "@template" in class Doctrine\Common\Collections\ArrayCollection was never imported. Did you maybe forget to add a "use" statement for this annotation?`

How can we fix it ?

**Comment by Ocramius** [comment] 2019-03-25 09:03
Duplicate of https://github.com/doctrine/collections/issues/180

Please check which component is trying to parse annotations from `ArrayCollection`.

**Closed by Ocramius** 2019-03-25 09:03 UTC
