### ISSUE TITLE
Use looser `callable` type in place of `Closure`

### ISSUE THREAD

**Issue by tyteen4a03** [doctrine/collections#378] opened 2023-07-31 09:56 UTC
Would it be possible for Collection methods to typehint for `callable` instead of `Closure` so I can pass non-anonymous functions to the methods?

**Comment by greg0ire** [comment] 2023-07-31 11:41
Have you considered using `Closure::fromCallable()`?

**Comment by tyteen4a03** [comment] 2023-07-31 13:28
Yes that's possible, but why not use a looser and 100% compatible type? AFAICT the code does not use characteristics only available to `Closure`s.

**Comment by greg0ire** [comment] 2023-07-31 14:35
Duplicate of https://github.com/doctrine/collections/issues/231

(and also, with first-class callable syntax, which creates closures, this is even simpler now than what I previously suggested)

**Closed as not planned by greg0ire** 2023-07-31 14:35 UTC

**Comment by derrabus** [comment] 2023-07-31 14:56
I've laid out my reasons for requiring closures here: https://github.com/doctrine/collections/pull/321#issuecomment-1227747872
