### ISSUE TITLE
Add the ability to add "INSTANCE OF" for Criteria Expression Comparison

### ISSUE THREAD

**Issue by trickeyone** [doctrine/collections#113] opened 2017-03-01 02:31 UTC
I don't know how many other people are in need of it, but dealing with a a relational DB and the Doctrine Discriminator mapping is really handy. That is, until you need to limit the results from a Collection to a relation that has a relation of a particular discriminator type.

For example:

```php
/**
 * @ORM\Entity()
 */
class ParentObject
{
    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="ChildObject", mappedBy="parentObject")
     */
    private $childObjects;

    public function getPublishedChildObjects()
    {
        $criteria = Criteria::create();
        $criteria->andWhere(
            Criteria::expr()->instanceOf('childObjects.status', Status\Published::class);
        );
        return $this->childObjects->matching($criteria);
    }
}

/**
 * @ORM\Entity()
 */
class ChildObject
{
    /**
     * @var ParentObject
     * @ORM\ManyToOne(targetEntity="ParentObject", inversedBy="childObject")
     */
    private $parentObject;

    /**
     * @var Status
     * @ORM\ManyToOne(targetEntity="Status")
     */
    private $status;
}

/**
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "draft" = "Status\Draft",
 *     "published" = "Status\Published"
 * })
 */
class Status
{
    private $id;
}

/* @var ParentObject $parentObject */
$parentObject = <Get ParentObject from query>;
$publishedChildObjects = $object1->getPublishedChildObjects();
```

The actual need is more complex with multiple status types. It would be nice to be able to do the above with collections.

**Comment by Ocramius** [comment] 2017-03-02 20:39
Duplicate of https://github.com/doctrine/doctrine2/issues/5908

**Comment by trickeyone** [comment] 2017-03-02 21:13
Thanks @Ocramius! Didn't know there was a request on the main doctrine2 project.

**Comment by trickeyone** [comment] 2018-10-18 06:43
As a note, I've found that if I use:
```php
$type1 = new Type/Type1();
$type2 = new Type/Type2();
Criteria::expr()->andWhere(
  'field',
  Criteria::expr()->in([$type1, $type2])
);
```
Where `Type/Type1` and `Type/Type2` are discriminators with IDs, the desired outcome can be achieved.

**Closed** 2020-07-27 17:53 UTC
Labels: Enhancement, Question

**Comment by 7ochem** [comment] 2021-09-29 13:18
I wanted to filter a collection by a specific type and ran into the same issue:

```
$object->getItems()->matching(
    Criteria::create()->where(
        Criteria::expr()->instanceOf(Some::class)
    )
);
```

But `instanceOf()` obviously does not exist. The "items" here is a collection of subtypes which all extend some base class.

If this is still a thing, then I could take a shot at this and try to add it to doctrine/collections and doctrine/orm

**Comment by trickeyone** [comment] 2021-09-29 20:03
@7ochem It looks like my PR (#249) was accepted and added to 1.6.8, which restored only strict-checking for scalar values. This re-enabled my original work-around. That said, I think having an equivalent of `INSTANCE OF` for collections would be extremely beneficial.
