### ISSUE TITLE
Why no reduce?

### ISSUE THREAD

**Issue by martixy** [doctrine/collections#116] opened 2017-03-16 16:51 UTC
Given the presence of `map` and `filter`, not having just `reduce` goes sort of against common sense and basic assumptions. We already have `forAll` and `exists` which are specific cases of `reduce`. Why not also have the general-purpose higher order function? Heck, it's kind of the highest higher-order function.

**Comment by Ocramius** [comment] 2017-03-16 16:51
Duplicate of https://github.com/doctrine/collections/issues/85

**Closed by Ocramius** 2017-03-16 16:51 UTC
